name: Builds

on:
  push:
    branches: ['**']

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 'Build'
    environment:
      name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - name: Setup nixbuild
        uses: nixbuild/nixbuild-action@v20
        with:
          nixbuild_token: ${{ secrets.NIXBUILD_TOKEN }}
          generate_summary_for: 'workflow'
      - name: Build
        run: |
          nix build \
            --print-build-logs \
            --builders "" \
            --max-jobs 100 \
            --eval-store auto \
            --store ssh-ng://eu.nixbuild.net \
            --accept-flake-config \
            . \
            .#dev